# Server Configuration
server.port=8080
spring.application.name=Smart-Campus-Operations-Hub

# Database Configuration (H2 for development)
spring.datasource.url=jdbc:h2:mem:smartcampusdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=root
spring.datasource.password=lavanya

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA Configuration
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Logging
logging.level.org.springframework.web=DEBUG
logging.level.com.Campus_Hub=DEBUG