package com.smartcampus.enums;

public enum NotificationType {
    BOOKING_APPROVED,
    BOOKING_REJECTED,
    BOOKING_CANCELLED,
    TICKET_STATUS_CHANGED,
    TICKET_ASSIGNED,
    TICKET_COMMENT_ADDED,
    TICKET_RESOLVED,
    SYSTEM_ANNOUNCEMENT
}
