spring.security.oauth2.client.registration.google.client-id=929559490122-216k92q1odm9njtbr562vur2339v22j3.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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


# ── OAuth2 – GitHub ─────────────────────────────────────────
spring.security.oauth2.client.registration.github.client-id=${Ov23liO1R9bX1KO3h5BT}
spring.security.oauth2.client.registration.github.client-secret=${72178eb33fa398a9e8af6a57915e0b7ebf7a1292}